### ISSUE TITLE
Dependencies: Libraries and PyTorch Version

### ISSUE THREAD

**Issue by zxgapollo** [fshamshirdar/place-recognition#1]
I'm really interested in visual place recognition and your marvelous implementation of this paper. However, the dependicies and the PyTorch version is not declared.

**Comment by fshamshirdar** [comment]
Thanks @zxgapollo, this code is not an actual implementation of the paper "Deep Learning Features at Scale for Visual Place Recognition". I used their model to finetune or retrain from scratch by KITTI dataset via TripletLoss. PyTorch v0.3.0 is used. I'll update the code and README soon!

**Comment by fshamshirdar** [comment]
You can download the pre-trained model from https://wiki.qut.edu.au/display/cyphy/Specific+PlacEs+Dataset+(SPED)+Dataset+and+deep+learning+models+for+visual+place+recognition and convert it to PyTorch by opensource conversion tools.

**Comment by zxgapollo** [comment]
Thanks a lot! I will try to retrain it. Looking forward to updated code and README.

**Comment by weiyunchen92** [comment]
@fshamshirdar hello! thanks for your implementation of the paper! I also want to fine tune the model with my own dataset. But do you still have the pre-trained model from the website? Because I couldn't download the weights of pre-trained model. If you still have it, could you send it to me? Thanks!!

**Comment by fshamshirdar** [comment]
Sure, but I can't share it here in Github. Share your email address with me and I will send you the PyTorch model.

**Comment by weiyunchen92** [comment]
@fshamshirdar my email address is oscarcwy92@gmail.com. Thank you so much!

**Comment by jsdd25** [comment]
@weiyunchen92, @fshamshirdar Hello! I also couldn't download the weights of pre-trained model. Could you send it to me? My email address is jsdd25888@gmail.com. Thank you so much!

**Comment by weiyunchen92** [comment]
@jsdd25 https://github.com/scutzetao/DLfeature_PlaceRecog_icra2017 you can download the weights of the pre-trained from this link.

**Comment by jsdd25** [comment]
@weiyunchen92 Thank you very much!

**Comment by FrederikWarburg** [comment]
@fshamshirdar will you share the converted weights? My email is frewar1905@gmail.com . Thank you very much!

**Comment by evandeng** [comment]
@fshamshirdar dear author, could you please share your converted weight in Pytorch with me, my email is successdzw@126.com, thank you so much.
