### ISSUE TITLE
Sample "index.txt" "pairs.txt"

### ISSUE THREAD

**Issue by zhanqan** [fshamshirdar/place-recognition#2]
Hello, I am interested in your implementation of this paper. But I don't figure out the format of  "index.txt" and "pairs.txt". Can you give me a example of "index.txt" and "pairs.txt"? Hope for your reply, thanks!

**Comment by fshamshirdar** [comment]
Hi, you don't need to provide pairs.txt file, "index.txt" should contain path to images. and "fGPS.txt" contains coordinates data for each image. "pair.txt" is automatically generated by the code based on the GPS data.
