### ISSUE TITLE
Any luck converting pre-trained caffe model to pytorch?

### ISSUE THREAD

**Issue by FrederikWarburg** [fshamshirdar/place-recognition#3]
Hi,

I'm trying to convert the pretrained model weights from https://github.com/scutzetao/DLfeature_PlaceRecog_icra2017 initialize your model weights. Did you have any luck converting the pretrained model to pytorch? 

Thanks in advance
Best

**Comment by fshamshirdar** [comment]
Please send me an email and I'll send you the converted weights. Have a look at #1 

Good luck
